// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABp9zcGLduM_HUUR4yT7xgXLDzaG0we6M',
    appId: '1:763856600585:web:c98d84ddd44bf8d6ad42d8',
    messagingSenderId: '763856600585',
    projectId: 'fb-test-4294f',
    authDomain: 'fb-test-4294f.firebaseapp.com',
    storageBucket: 'fb-test-4294f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjIZbvAzMhqnf0OE3A1XcazbPWxfazNAg',
    appId: '1:763856600585:android:ae6653255dd36e4fad42d8',
    messagingSenderId: '763856600585',
    projectId: 'fb-test-4294f',
    storageBucket: 'fb-test-4294f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-uMSGQJXVphgtXkmjmsIiRnA9YFPeFwY',
    appId: '1:763856600585:ios:b9f92f781f76dcd7ad42d8',
    messagingSenderId: '763856600585',
    projectId: 'fb-test-4294f',
    storageBucket: 'fb-test-4294f.appspot.com',
    iosBundleId: 'com.example.fbTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-uMSGQJXVphgtXkmjmsIiRnA9YFPeFwY',
    appId: '1:763856600585:ios:df1ceb1056f4f49cad42d8',
    messagingSenderId: '763856600585',
    projectId: 'fb-test-4294f',
    storageBucket: 'fb-test-4294f.appspot.com',
    iosBundleId: 'com.example.fbTest.RunnerTests',
  );
}
